apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-35.189.200.254
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.194
          port: 22
        public:
          address: 35.189.200.254
          port: 22
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-35.205.216.95
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.192
          port: 22
        public:
          address: 35.205.216.95
          port: 22
kind: List
